BEGIN TRANSACTION;
DROP TABLE IF EXISTS Email;
DROP TABLE IF EXISTS User;
CREATE TABLE IF NOT EXISTS User (
    UserID INTEGER PRIMARY KEY,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Email TEXT NOT NULL
    Aes_key BLOB
);
CREATE TABLE IF NOT EXISTS Email (
    EmailID INTEGER PRIMARY KEY,
    SenderID INTEGER,
    ReceiverID INTEGER,
    Subject TEXT,
    Body TEXT,
    FOREIGN KEY (SenderID) REFERENCES User(UserID),
    FOREIGN KEY (ReceiverID) REFERENCES User(UserID)
);
COMMIT;