DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Email;
CREATE TABLE IF NOT EXISTS User (
    UserID INTEGER PRIMARY KEY,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Email TEXT NOT NULL,
    Key TEXT
);
CREATE TABLE IF NOT EXISTS Email (
    EmailID INTEGER PRIMARY KEY,
    SenderID INTEGER,
    ReceiverID INTEGER,
    Subject TEXT,
    Body TEXT,
    Seen BOOLEAN,
    FOREIGN KEY (SenderID) REFERENCES User(UserID),
    FOREIGN KEY (ReceiverID) REFERENCES User(UserID)
);